# Generated by Django 4.2 on 2024-09-16 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('method', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'unknown'), (1, 'get'), (2, 'post'), (3, 'put'), (4, 'patch'), (5, 'delete'), (6, 'head'), (7, 'option')], default=0, null=True)),
                ('uri', models.TextField(blank=True, null=True)),
                ('status', models.PositiveIntegerField(blank=True, null=True)),
                ('size', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(1073741824)])),
            ],
        ),
    ]
